export enum ErrorCodes {
    MISSING_USER_ID = "MISSING_USER_ID",
    INVALID_PLATFORM_TYPE = "INVALID_PLATFORM_TYPE",
    PLATFORM_TYPE_MISMATCH = "PLATFORM_TYPE_MISMATCH",
    MISSING_CONTENT_TYPE = "MISSING_CONTENT_TYPE",
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
  }
  